### ISSUE TITLE
Pytest error

### ISSUE THREAD

**Issue by Avhijit-Nair** [Avhijit-codeboy/speakNotes#8]
Getting following error on running jobs of speakNotes.yml file

__platform linux -- Python 3.8.5, pytest-6.1.0, py-1.9.0, pluggy-0.13.1__
__rootdir: /home/runner/work/speakNotes/speakNotes__
collected 0 items

============================ no tests ran in 0.01s =============================
__Error: Process completed with exit code 5.__

Please resolve this.

**Comment by cmccandless** [comment]
This repository contains no tests. The `pytest` output is correct.

**Comment by Trimankaur** [comment]
https://github.com/pytest-dev/pytest/issues/2393 can help

**Comment by Avhijit-Nair** [comment]
Its open to everyone, so you can go ahead and make a PR after adding relevant test cases.
